#docker compose file for the project
version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - bus-booking
      - bus-service
      - user-service
      - agent-service
      - booking-service
      - error-handling
    networks:
      - bus-network

  bus-booking:
    build: ./bus-booking
    ports:
      - "8001:8001"
    networks:
      - bus-network

  bus-service:
    build: ./bus-service
    ports:
      - "8002:8002"
    networks:
      - bus-network

  user-service:
    build: ./user-service
    ports:
      - "8003:8003"
    networks:
      - bus-network

  agent-service:
    build: ./agent-service
    ports:
      - "8006:8006"
    networks:
      - bus-network

  booking-service:
    build: ./booking-service
    ports:
      - "8007:8007"
    networks:
      - bus-network

  error-handling:
    build: ./error_handling
    ports:
      - "8005:8005"
    networks:
      - bus-network

networks:
  bus-network:
    driver: bridge 